[package]
name = "myapp"
version = "0.1.0"
authors = ["Jack <jack.newman12@gmail.com>"]
edition = "2018"

[profile.release]
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.6"
rocket_contrib = "0.4.6"
serde = {version = "1.0.117", features = ["derive"]}
serialport = "4.0.0"
rust-embed = "5.7.0"
rust-embed-rocket = {git = "https://github.com/peacememories/rust-embed-rocket"}