name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Build
      with:
        toolchain: nightly
    - run: npm install
    - run: npm run build  
    - run: cargo build --release
